Try out M1 runners

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,10 +14,12 @@ env:
 
 jobs:
   macos_build:
-    name: MacOS 
+    name: MacOS (${{ matrix.OS }})
     strategy:
       fail-fast: true
-    runs-on: macos-12
+      matrix:
+        OS: ["macos-12", "macos-14"]
+    runs-on: ${{ matrix.OS }}
     env:
       LLVM_VERSION: 14
     steps:
@@ -53,48 +55,48 @@ jobs:
           name: macos-intel-binaries
           if-no-files-found: error
           
-  macos_arm_build:
-      name: MacOS (Arm64)
-      strategy:
-        fail-fast: true
-      runs-on: macos-aarch64
-      if: startsWith(github.ref, 'refs/tags/v')
-      continue-on-error: true
-      steps:
-        - uses: actions/checkout@v3
-          with:
-            fetch-depth: 0 
+  # macos_arm_build:
+  #     name: MacOS (Arm64)
+  #     strategy:
+  #       fail-fast: true
+  #     runs-on: macos-aarch64
+  #     if: startsWith(github.ref, 'refs/tags/v')
+  #     continue-on-error: true
+  #     steps:
+  #       - uses: actions/checkout@v3
+  #         with:
+  #           fetch-depth: 0 
 
-        - uses: actions/setup-java@v3
-          with:
-            distribution: 'temurin' 
-            java-version: '17'
-            cache: 'sbt'
+  #       - uses: actions/setup-java@v3
+  #         with:
+  #           distribution: 'temurin' 
+  #           java-version: '17'
+  #           cache: 'sbt'
 
-        - name: Install LLVM
-          run: brew install llvm@$LLVM_VERSION
+  #       - name: Install LLVM
+  #         run: brew install llvm@$LLVM_VERSION
 
-        - name: Install SBT 
-          run: brew install sbt
+  #       - name: Install SBT 
+  #         run: brew install sbt
 
-        - name: Sets env vars for release
-          if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
-          run: |
-            echo "SCALANATIVE_MODE=release-fast" >> $GITHUB_ENV
+  #       - name: Sets env vars for release
+  #         if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
+  #         run: |
+  #           echo "SCALANATIVE_MODE=release-fast" >> $GITHUB_ENV
 
-        - name: Sets env vars for LLVM
-          run: |
-            echo "LLVM_BIN=/opt/homebrew/opt/llvm@$LLVM_VERSION/bin" >> $GITHUB_ENV
+  #       - name: Sets env vars for LLVM
+  #         run: |
+  #           echo "LLVM_BIN=/opt/homebrew/opt/llvm@$LLVM_VERSION/bin" >> $GITHUB_ENV
 
-        - name: CI and build the binary
-          run: sbt ci buildPlatformBinary
+  #       - name: CI and build the binary
+  #         run: sbt ci buildPlatformBinary
 
-        - name: Upload artifacts
-          uses: actions/upload-artifact@v4
-          with:
-            path: bin/sn-bindgen-*
-            name: macos-arm-binaries
-            if-no-files-found: error
+  #       - name: Upload artifacts
+  #         uses: actions/upload-artifact@v4
+  #         with:
+  #           path: bin/sn-bindgen-*
+  #           name: macos-arm-binaries
+  #           if-no-files-found: error
 
   linux_build:
       name: Linux
@@ -232,7 +234,7 @@ jobs:
 
   release:
     if: ${{ always() }}
-    needs: [linux_build, linux_arm64_build, windows_build, macos_build, macos_arm_build]
+    needs: [linux_build, linux_arm64_build, windows_build, macos_build]
     name: Release
     runs-on: ubuntu-20.04
     env: 
